### ISSUE TITLE
Add options to look for index file if they are not provided

### ISSUE THREAD

**Issue by oscarr-reyes** [adamhalasz/diet-static#2]
in order to make pages to be a little protected by people that could figure out where the views are being called, we would just not show that this file is an index in our url, and not even show that it is an html

would be better if we have options like `showIndex` and `showScriptName` in order to achieve them

**Comment by frank-dspeed** [comment]
i don't understand what that means use the 404 routing? or what?

**Comment by 4strid** [comment]
Not sure if this is exactly what he means, but connect-static has a similar feature called aliasing, which for instance lets you alias '/' as '/index.html' which automatically serves index.html of any directory while not displaying it in the URL. That'd certainly be nice to have.

**Comment by frank-dspeed** [comment]
@cutejs your joking right?

simple mount your app to / and render index in what ever condition you like its a 1 liner why does some one use a framework when he can't code :)

**Comment by frank-dspeed** [comment]
This can be closed
